/* tslint:disable */
/* eslint-disable */
/**
 * Vidra API
 * REST API for Vidra video downloader and manager
 *
 * The version of the OpenAPI document: 1.0
 * Contact: martin.yordanov@vexbyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HandlersVideoResponse } from './handlers-video-response';

export interface HandlersPaginatedVideoResponse {
    'currentPage'?: number;
    'limit'?: number;
    'totalCount'?: number;
    'totalPages'?: number;
    'videos'?: Array<HandlersVideoResponse>;
}

