/* tslint:disable */
/* eslint-disable */
/**
 * Vidra API
 * REST API for Vidra video downloader and manager
 *
 * The version of the OpenAPI document: 1.0
 * Contact: martin.yordanov@vexbyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HandlersCreateVideoRequest } from '../models';
// @ts-ignore
import type { HandlersMetadataRequest } from '../models';
// @ts-ignore
import type { HandlersPaginatedVideoResponse } from '../models';
// @ts-ignore
import type { HandlersUpdateVideoRequest } from '../models';
// @ts-ignore
import type { HandlersVideoResponse } from '../models';
// @ts-ignore
import type { ServicesDownloadProgressDTO } from '../models';
// @ts-ignore
import type { ServicesVideoMetadata } from '../models';
/**
 * VideosApi - axios parameter creator
 */
export const VideosApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a new video record and start background download
         * @summary Create a new video download task
         * @param {HandlersCreateVideoRequest} video Video details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVideo: async (video: HandlersCreateVideoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'video' is not null or undefined
            assertParamExists('createVideo', 'video', video)
            const localVarPath = `/api/videos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(video, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a video record by ID and its associated files
         * @summary Delete a video
         * @param {string} id Video ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteVideo: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteVideo', 'id', id)
            const localVarPath = `/api/videos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetch available formats and metadata for a given URL using yt-dlp
         * @summary Get video metadata and options
         * @param {HandlersMetadataRequest} request Video URL
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMetadata: async (request: HandlersMetadataRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('getMetadata', 'request', request)
            const localVarPath = `/api/videos/metadata`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the current download progress of a video by ID
         * @summary Get download progress
         * @param {string} id Video ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProgress: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getProgress', 'id', id)
            const localVarPath = `/api/videos/{id}/progress`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get details of a specific video
         * @summary Get a video by ID
         * @param {string} id Video ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVideo: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getVideo', 'id', id)
            const localVarPath = `/api/videos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the current download progress for all active video downloads
         * @summary List all video download progress
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAllProgress: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/videos/progress`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a paginated list of all videos with optional searching and ordering
         * @summary List all videos
         * @param {string} [search] Search by name or URL
         * @param {string} [order] Order by (name_asc, name_desc, created_at_asc, created_at_desc, status_asc, status_desc)
         * @param {number} [page] Page number (default: 1)
         * @param {number} [limit] Number of items per page (default: 10)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVideos: async (search?: string, order?: string, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/videos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update video details like name
         * @summary Update a video
         * @param {string} id Video ID
         * @param {HandlersUpdateVideoRequest} video Updated video details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateVideo: async (id: string, video: HandlersUpdateVideoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateVideo', 'id', id)
            // verify required parameter 'video' is not null or undefined
            assertParamExists('updateVideo', 'video', video)
            const localVarPath = `/api/videos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(video, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VideosApi - functional programming interface
 */
export const VideosApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VideosApiAxiosParamCreator(configuration)
    return {
        /**
         * Create a new video record and start background download
         * @summary Create a new video download task
         * @param {HandlersCreateVideoRequest} video Video details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createVideo(video: HandlersCreateVideoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersVideoResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createVideo(video, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VideosApi.createVideo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete a video record by ID and its associated files
         * @summary Delete a video
         * @param {string} id Video ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteVideo(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteVideo(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VideosApi.deleteVideo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fetch available formats and metadata for a given URL using yt-dlp
         * @summary Get video metadata and options
         * @param {HandlersMetadataRequest} request Video URL
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMetadata(request: HandlersMetadataRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ServicesVideoMetadata>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMetadata(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VideosApi.getMetadata']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get the current download progress of a video by ID
         * @summary Get download progress
         * @param {string} id Video ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProgress(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ServicesDownloadProgressDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProgress(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VideosApi.getProgress']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get details of a specific video
         * @summary Get a video by ID
         * @param {string} id Video ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVideo(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersVideoResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getVideo(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VideosApi.getVideo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get the current download progress for all active video downloads
         * @summary List all video download progress
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAllProgress(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: ServicesDownloadProgressDTO; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listAllProgress(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VideosApi.listAllProgress']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get a paginated list of all videos with optional searching and ordering
         * @summary List all videos
         * @param {string} [search] Search by name or URL
         * @param {string} [order] Order by (name_asc, name_desc, created_at_asc, created_at_desc, status_asc, status_desc)
         * @param {number} [page] Page number (default: 1)
         * @param {number} [limit] Number of items per page (default: 10)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listVideos(search?: string, order?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersPaginatedVideoResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listVideos(search, order, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VideosApi.listVideos']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update video details like name
         * @summary Update a video
         * @param {string} id Video ID
         * @param {HandlersUpdateVideoRequest} video Updated video details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateVideo(id: string, video: HandlersUpdateVideoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandlersVideoResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateVideo(id, video, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VideosApi.updateVideo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VideosApi - factory interface
 */
export const VideosApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VideosApiFp(configuration)
    return {
        /**
         * Create a new video record and start background download
         * @summary Create a new video download task
         * @param {HandlersCreateVideoRequest} video Video details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVideo(video: HandlersCreateVideoRequest, options?: RawAxiosRequestConfig): AxiosPromise<HandlersVideoResponse> {
            return localVarFp.createVideo(video, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete a video record by ID and its associated files
         * @summary Delete a video
         * @param {string} id Video ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteVideo(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteVideo(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Fetch available formats and metadata for a given URL using yt-dlp
         * @summary Get video metadata and options
         * @param {HandlersMetadataRequest} request Video URL
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMetadata(request: HandlersMetadataRequest, options?: RawAxiosRequestConfig): AxiosPromise<ServicesVideoMetadata> {
            return localVarFp.getMetadata(request, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the current download progress of a video by ID
         * @summary Get download progress
         * @param {string} id Video ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProgress(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ServicesDownloadProgressDTO> {
            return localVarFp.getProgress(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Get details of a specific video
         * @summary Get a video by ID
         * @param {string} id Video ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVideo(id: string, options?: RawAxiosRequestConfig): AxiosPromise<HandlersVideoResponse> {
            return localVarFp.getVideo(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the current download progress for all active video downloads
         * @summary List all video download progress
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAllProgress(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: ServicesDownloadProgressDTO; }> {
            return localVarFp.listAllProgress(options).then((request) => request(axios, basePath));
        },
        /**
         * Get a paginated list of all videos with optional searching and ordering
         * @summary List all videos
         * @param {string} [search] Search by name or URL
         * @param {string} [order] Order by (name_asc, name_desc, created_at_asc, created_at_desc, status_asc, status_desc)
         * @param {number} [page] Page number (default: 1)
         * @param {number} [limit] Number of items per page (default: 10)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVideos(search?: string, order?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<HandlersPaginatedVideoResponse> {
            return localVarFp.listVideos(search, order, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Update video details like name
         * @summary Update a video
         * @param {string} id Video ID
         * @param {HandlersUpdateVideoRequest} video Updated video details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateVideo(id: string, video: HandlersUpdateVideoRequest, options?: RawAxiosRequestConfig): AxiosPromise<HandlersVideoResponse> {
            return localVarFp.updateVideo(id, video, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VideosApi - object-oriented interface
 */
export class VideosApi extends BaseAPI {
    /**
     * Create a new video record and start background download
     * @summary Create a new video download task
     * @param {HandlersCreateVideoRequest} video Video details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createVideo(video: HandlersCreateVideoRequest, options?: RawAxiosRequestConfig) {
        return VideosApiFp(this.configuration).createVideo(video, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete a video record by ID and its associated files
     * @summary Delete a video
     * @param {string} id Video ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteVideo(id: string, options?: RawAxiosRequestConfig) {
        return VideosApiFp(this.configuration).deleteVideo(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fetch available formats and metadata for a given URL using yt-dlp
     * @summary Get video metadata and options
     * @param {HandlersMetadataRequest} request Video URL
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMetadata(request: HandlersMetadataRequest, options?: RawAxiosRequestConfig) {
        return VideosApiFp(this.configuration).getMetadata(request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get the current download progress of a video by ID
     * @summary Get download progress
     * @param {string} id Video ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getProgress(id: string, options?: RawAxiosRequestConfig) {
        return VideosApiFp(this.configuration).getProgress(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get details of a specific video
     * @summary Get a video by ID
     * @param {string} id Video ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getVideo(id: string, options?: RawAxiosRequestConfig) {
        return VideosApiFp(this.configuration).getVideo(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get the current download progress for all active video downloads
     * @summary List all video download progress
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listAllProgress(options?: RawAxiosRequestConfig) {
        return VideosApiFp(this.configuration).listAllProgress(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get a paginated list of all videos with optional searching and ordering
     * @summary List all videos
     * @param {string} [search] Search by name or URL
     * @param {string} [order] Order by (name_asc, name_desc, created_at_asc, created_at_desc, status_asc, status_desc)
     * @param {number} [page] Page number (default: 1)
     * @param {number} [limit] Number of items per page (default: 10)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listVideos(search?: string, order?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return VideosApiFp(this.configuration).listVideos(search, order, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update video details like name
     * @summary Update a video
     * @param {string} id Video ID
     * @param {HandlersUpdateVideoRequest} video Updated video details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateVideo(id: string, video: HandlersUpdateVideoRequest, options?: RawAxiosRequestConfig) {
        return VideosApiFp(this.configuration).updateVideo(id, video, options).then((request) => request(this.axios, this.basePath));
    }
}

