/* tslint:disable */
/* eslint-disable */
/**
 * Vidra API
 * REST API for Vidra video downloader and manager
 *
 * The version of the OpenAPI document: 1.0
 * Contact: martin.yordanov@vexbyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * YtdlpApi - axios parameter creator
 */
export const YtdlpApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Execute yt-dlp -U to update the binary
         * @summary Update yt-dlp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateYtdlp: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/yt-dlp/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * YtdlpApi - functional programming interface
 */
export const YtdlpApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = YtdlpApiAxiosParamCreator(configuration)
    return {
        /**
         * Execute yt-dlp -U to update the binary
         * @summary Update yt-dlp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateYtdlp(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: string; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateYtdlp(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['YtdlpApi.updateYtdlp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * YtdlpApi - factory interface
 */
export const YtdlpApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = YtdlpApiFp(configuration)
    return {
        /**
         * Execute yt-dlp -U to update the binary
         * @summary Update yt-dlp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateYtdlp(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: string; }> {
            return localVarFp.updateYtdlp(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * YtdlpApi - object-oriented interface
 */
export class YtdlpApi extends BaseAPI {
    /**
     * Execute yt-dlp -U to update the binary
     * @summary Update yt-dlp
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateYtdlp(options?: RawAxiosRequestConfig) {
        return YtdlpApiFp(this.configuration).updateYtdlp(options).then((request) => request(this.axios, this.basePath));
    }
}

