/* tslint:disable */
/* eslint-disable */
/**
 * Vidra API
 * REST API for Vidra video downloader and manager
 *
 * The version of the OpenAPI document: 1.0
 * Contact: martin.yordanov@vexbyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HandlersErrorResponse } from './handlers-error-response';

export interface HandlersPaginatedErrorResponse {
    'currentPage'?: number;
    'errors'?: Array<HandlersErrorResponse>;
    'limit'?: number;
    'totalCount'?: number;
    'totalPages'?: number;
}

