/* tslint:disable */
/* eslint-disable */
/**
 * Vidra API
 * REST API for Vidra video downloader and manager
 *
 * The version of the OpenAPI document: 1.0
 * Contact: martin.yordanov@vexbyte.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const ServicesDownloadStatus = {
    StatusPending: 'pending',
    StatusDownloading: 'downloading',
    StatusEncoding: 'encoding',
    StatusFinished: 'completed',
    StatusError: 'error'
} as const;

export type ServicesDownloadStatus = typeof ServicesDownloadStatus[keyof typeof ServicesDownloadStatus];



